### ISSUE TITLE
Mapping the roadmap to the sprint model

### ISSUE THREAD

**Issue by blahah** [mozillascience/fellows-class-2015#21]
I'm looking over the [roadmap](https://github.com/mozillascience/fellows-class-2015/blob/master/roadmap.md) and trying to map the tasks/deliverables to the sprint model of working. In particular, my feeling is that the deadlines might need to be changed to account for sprints - and this only really applies to the explore phase (the prototype phase is already sprint-adapted!).

Here's what I've got:
### Explore phase
- **Intro and Exploring Problems/Challenges** [OK]
  - the interview is independent of the project model
  - we've interpreted the writing exercise and blog post so that they describe higher-level ideas rather than specific projects
- **Idea Development** [questions]
  - [Describing and testing your idea](https://github.com/mozillascience/fellows-class-2015/blob/master/explore/2-project_description_exercise.md). We've [written up the general idea of doing sprints, and several sprint project ideas](https://github.com/mozillascience/fellows-class-2015/blob/master/fellowship_sprints.md). Does this satisfy this task?
  - [User/Collaborator personas & pathways exercise](https://github.com/mozillascience/fellows-class-2015/blob/master/explore/2-personas_and_pathways.md). This would be a great task to do for each sprint project - is it OK for us to do it that way? So the product for this task will be created as we start each sprint.
  - [Resource requirements](https://github.com/mozillascience/fellows-class-2015/blob/master/explore/2-resources_requirements.md) & [sustainability plan](https://github.com/mozillascience/fellows-class-2015/blob/master/explore/2-sustainability_plan.md). As above, this seems suited to a per-sprint document, written at the start of each sprint.
- **Project Planning and Pitching** [questions]
  - All of these seem to me like sprint-specific things. Is that a reasonable interpretation?

cc @joeyklee

**Comment by blahah** [comment]
Just expanding a bit - if all the above stuff is a per-sprint task list, we'd perhaps take a day at the beginning of each sprint to just to planning and work through these exercises. And then one at the end to do write-up and reflection. Thoughts MSL?

**Comment by zee-moz** [comment]
Richard,  Thanks for writing and thinking this through! 

We'd come up with the Explore phase deliverables to strengthen project ideas and prepare for subsequent phases-- so yes they are designed at as per project tasks. 

We've since responded to your request for a faster, more sprightly Sprint model by condensing and stripping down the upfront thinking and writing tasks and putting them into the Entry and Exit surveys which deliverables on the Roadmap under that Protoyping phase... You can see them there now, though I don't know if @auremoser or @acabunoc have talked you through them yet... Perhaps that's planned on the call for today. Some of the in-depth explore thinking about users and pitching the idea got lost for the sake of speediness... 

Looks like you're thinking about process over there, and we're responding and thinking about process over here, and we've missed the bit where we work together to co-design a process. I know @auremoser is super busy right now prepping for Berlin and it's up to her, but I'd would LOVE to coordinate have conversations and collaborate a bit better on the design of the fellowship process and deliverables-- find time and a format for doing that. I think the fact that we're scattered about the globe makes it tricky, but we'll definitely design better materials if we do it together (duh). 

@auremoser @acabunoc @kaythaney what do you think?

**Comment by auremoser** [comment]
Sorry, late to this party. I think I suggested in my email to you and Joey that you choose 3 projects max to complete all the Explore tasks for. And then ideally we can all move on to the Prototype phase with the surveys as checkpoints, bookending each sprint with some thought about that project and its users.

@zee-moz is correct, the surveys were designed to cover you on a "quick" version of the explore tasks for each sprint. I'm sorry if I didn't include you all in the design process for the Prototype phase, I was trying to accommodate both the sprint and the single project styles on the same calendar cycle, and maybe that doesn't make sense:/. In any case, the call today should address those workflows and talk through any kinks. 

I'm fine with you doing the surveys and an abbreviated form of the explore exercises for each sprint, but that might take a lot of time, so if you want to just do the surveys and reflect on those results after via the blog task in the Prototype phase, I dig it.

**Comment by blahah** [comment]
Thanks both of you for explaining, and sorry if I missed this being covered in previous comms.

So just to be clear - with the next entry/exit surveys, we no longer need to do all the explore activities I queried above for each sprint (or for 3 as you mentioned)? I definitely agree that doing all the exercises per sprint would be time intensive.

**Comment by auremoser** [comment]
No worries, I probably didn't express myself well, typical.

That was the plan! That said, I think I recommended doing the explore phase tasks for 3 projects, maybe you can Joey could each do it for your "favorite" sprint project and leave it at that (so 2 projects total, more aligned with your single track comrades who are also only doing those exercises once). I don't want to invalidate the time it took to write those tasks, and think it would be helpful to go through that thought process at least once, it will probably inform how you answer the sprint surveys.

Hopefully that makes sense and if not we can chat in the call!

**Comment by auremoser** [comment]
I'm closing this, but we'll still have it logged in case we want to readdress as we march through the prototype phase :)
